#############################################################################
# Makefile for building: test
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  ../test/test.pro
# Template: app
# Command: /opt/Qt5.3.1/5.3/gcc/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile ../test/test.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I../test -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/opt/Qt5.3.1/5.3/gcc/include -I/opt/Qt5.3.1/5.3/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt5.3.1/5.3/gcc -Wl,-rpath,/opt/Qt5.3.1/5.3/gcc/lib
LIBS          = $(SUBLIBS) /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ml.so -L/opt/Qt5.3.1/5.3/gcc/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt5.3.1/5.3/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Plate.cpp \
		OCR.cpp \
		main.cpp \
		DetectRegions.cpp 
OBJECTS       = Plate.o \
		OCR.o \
		main.o \
		DetectRegions.o
DIST          = /opt/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf \
		../test/test.pro Plate.cpp \
		OCR.cpp \
		main.cpp \
		DetectRegions.cpp
QMAKE_TARGET  = test
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = test


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../test/test.pro /opt/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf /opt/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf \
		/opt/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf \
		../test/test.pro \
		/opt/Qt5.3.1/5.3/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile ../test/test.pro
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf:
/opt/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf:
../test/test.pro:
/opt/Qt5.3.1/5.3/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile ../test/test.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/test1.0.0 || mkdir -p .tmp/test1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/test1.0.0/ && $(COPY_FILE) --parents Plate.h OCR.h DetectRegions.h .tmp/test1.0.0/ && $(COPY_FILE) --parents Plate.cpp OCR.cpp main.cpp DetectRegions.cpp .tmp/test1.0.0/ && (cd `dirname .tmp/test1.0.0` && $(TAR) test1.0.0.tar test1.0.0 && $(COMPRESS) test1.0.0.tar) && $(MOVE) `dirname .tmp/test1.0.0`/test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Plate.o: Plate.cpp Plate.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv/cvaux.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/legacy/legacy.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/legacy/blobtrack.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plate.o Plate.cpp

OCR.o: OCR.cpp OCR.h \
		Plate.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv/cvaux.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/legacy/legacy.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/legacy/blobtrack.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp \
		/usr/local/include/opencv/ml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OCR.o OCR.cpp

main.o: main.cpp /usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv/cvaux.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/legacy/legacy.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/legacy/blobtrack.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp \
		/usr/local/include/opencv/ml.h \
		DetectRegions.h \
		Plate.h \
		OCR.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DetectRegions.o: DetectRegions.cpp DetectRegions.h \
		Plate.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv/cvaux.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/legacy/legacy.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/legacy/blobtrack.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DetectRegions.o DetectRegions.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

